# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0015_auto_20160503_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='Keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('type', models.CharField(choices=[('TWITTER', 'Twitter')], default='TWITTER', max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=50, verbose_name='Status')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Disaster', verbose_name='Disaster')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'get_latest_by': 'updated',
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportaggregator.Source', verbose_name='Source'),
        ),
    ]
