# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportaggregator', '0002_auto_20160510_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
    ]
