# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 07:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('temperature', models.PositiveIntegerField(default=0, verbose_name='Temperature')),
                ('humidity', models.PositiveIntegerField(default=0, verbose_name='Humidity')),
                ('pressure', models.PositiveIntegerField(default=0, verbose_name='Pressure')),
                ('wind_speed', models.PositiveIntegerField(default=0, verbose_name='Wind Speed')),
                ('wind_direction', models.PositiveIntegerField(default=0, verbose_name='Wind Direction')),
                ('day_rain', models.PositiveIntegerField(default=0, verbose_name='Day Rain')),
                ('rain_rate', models.PositiveIntegerField(default=0, verbose_name='Rain Rate')),
                ('uv_index', models.PositiveIntegerField(default=0, verbose_name='UV Index')),
                ('solar_radiation', models.PositiveIntegerField(default=0, verbose_name='Solar Radiation')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'get_latest_by': 'updated',
            },
        ),
        migrations.CreateModel(
            name='AWSStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='awsreport',
            name='awsstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automaticweathersystem.AWSStation', verbose_name='AWS Station'),
        ),
    ]
