# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 10:19
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaticweathersystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsreport',
            name='day_rain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Day Rain'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='humidity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='pressure',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pressure'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='rain_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Rain Rate'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='solar_radiation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Solar Radiation'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='uv_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='UV Index'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='wind_direction',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wind Direction'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='wind_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Wind Speed'),
        ),
    ]
