# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaticweathersystem', '0002_auto_20160425_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsreport',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperature'),
        ),
    ]
