# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 14:45
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automaticweathersystem', '0003_auto_20160509_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsreport',
            name='awsstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automaticweathersystem.AWSStation', verbose_name='AWS station'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='day_rain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Day rain'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='rain_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Rain rate'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='solar_radiation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Solar radiation'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='uv_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='UV index'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='wind_direction',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wind direction'),
        ),
        migrations.AlterField(
            model_name='awsreport',
            name='wind_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Wind speed'),
        ),
    ]
