# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automaticweathersystem', '0004_auto_20160529_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awsreport',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
    ]
