# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automaticweathersystem', '0007_auto_20160730_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreport',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Censor reports'},
        ),
        migrations.AlterModelOptions(
            name='sensorstation',
            options={'verbose_name_plural': 'Censor stations'},
        ),
    ]
