# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-08 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automaticweathersystem', '0008_auto_20161021_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreport',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Sensor reports'},
        ),
        migrations.AlterModelOptions(
            name='sensorstation',
            options={'verbose_name_plural': 'Sensor stations'},
        ),
    ]
