# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 07:41
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0008_auto_20160416_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('file', models.FileField(blank=True, null=True, upload_to='reporting/attachment/', verbose_name='File')),
            ],
            options={
                'ordering': ['-report'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=100, verbose_name='Type')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Content')),
                ('text_id', models.TextField(blank=True, verbose_name='Text ID')),
                ('text_author', models.TextField(blank=True, verbose_name='Text author')),
                ('text_title', models.TextField(blank=True, verbose_name='Text title')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to='reporting/report/', verbose_name='File')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'get_latest_by': 'updated',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Content')),
                ('disaster_attached', models.ManyToManyField(blank=True, related_name='template_attached', to='reports.Disaster', verbose_name='Attached disaster')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'get_latest_by': 'updated',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reporting.Template', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reporting.Report', verbose_name='Report'),
        ),
    ]
