# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('file', models.TextField(blank=True, null=True, verbose_name='File')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('text_author', models.TextField(blank=True, null=True, verbose_name='Text_author')),
                ('text_title', models.TextField(blank=True, null=True, verbose_name='Text_title')),
                ('file', models.TextField(blank=True, null=True, verbose_name='File')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'get_latest_by': 'updated',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('content', models.CharField(max_length=50, verbose_name='Content')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'get_latest_by': 'updated',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reporting.Template', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='reporting.Report', verbose_name='Report'),
        ),
    ]
