# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 15:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='report',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='report',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='template',
            name='disaster_attached',
            field=models.ManyToManyField(blank=True, related_name='template_attached', to='reports.Disaster', verbose_name='Disaster attached'),
        ),
    ]
