# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 01:00
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'get_latest_by': 'created', 'ordering': ['-report']},
        ),
        migrations.RemoveField(
            model_name='template',
            name='type',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='report',
            name='text_id',
            field=models.TextField(blank=True, verbose_name='Text ID'),
        ),
        migrations.AddField(
            model_name='template',
            name='disaster_attached',
            field=models.ManyToManyField(blank=True, related_name='template_attached', to='reports.Disaster', verbose_name='Attached disaster'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reporting/attachment/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reporting.Report', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reporting/report/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text_author',
            field=models.TextField(blank=True, default='', verbose_name='Text author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='text_title',
            field=models.TextField(blank=True, default='', verbose_name='Text title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content'),
        ),
    ]
