# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20160422_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
    ]
