# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20160531_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Templates'},
        ),
    ]
