# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160426_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elibrary',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='elibrary',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.DeleteModel(
            name='ELibrary',
        ),
    ]
