# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160426_1612'),
        ('website', '0003_auto_20160426_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='categories.Category', verbose_name='Categories'),
        ),
    ]
