# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160426_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachment',
        ),
        migrations.AddField(
            model_name='attachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Post', verbose_name='Post'),
        ),
    ]
