# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 08:30
from __future__ import unicode_literals

import common.validators
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_post_slideshow_image_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slideshow_image_crop',
        ),
        migrations.AddField(
            model_name='post',
            name='test_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='website/crop_image/', validators=[common.validators.FileSizeValidator(1)]),
        ),
        migrations.AddField(
            model_name='post',
            name='test_image_cropping',
            field=image_cropping.fields.ImageRatioField('test_image', '770x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='test image cropping'),
        ),
    ]
