# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 08:31
from __future__ import unicode_literals

import common.validators
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160428_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='test_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='website/test_image/', validators=[common.validators.FileSizeValidator(1)]),
        ),
    ]
