# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 08:55
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160428_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='test_image_cropping',
        ),
        migrations.AddField(
            model_name='post',
            name='slideshow_image_crop',
            field=image_cropping.fields.ImageRatioField('slideshow_image', '770x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='slideshow image crop'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slideshow_enabled',
            field=models.BooleanField(default=True, verbose_name='Slideshow enabled'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slideshow_image',
            field=models.ImageField(blank=True, null=True, upload_to='website/slideshow_image/', validators=[common.validators.FileSizeValidator(1)], verbose_name='Slideshow image'),
        ),
    ]
