# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160428_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slideshow_image_thumb',
            field=image_cropping.fields.ImageRatioField('slideshow_image', '70x70', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Slideshow image thumb (70x70 px)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_text',
            field=models.TextField(blank=True, verbose_name='Author text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slideshow_enabled',
            field=models.BooleanField(default=False, verbose_name='Slideshow enabled'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slideshow_image_crop',
            field=image_cropping.fields.ImageRatioField('slideshow_image', '770x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Slideshow image crop (770x400 px)'),
        ),
    ]
