# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 10:08
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160428_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slideshow_image_post',
            field=image_cropping.fields.ImageRatioField('slideshow_image', '750x390', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Slideshow image post (750x390 px)'),
        ),
    ]
