# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20160430_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='siteheader',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Categories'),
            preserve_default=False,
        ),
    ]
