# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 03:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20160430_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Content')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'ordering': ['pk'],
                'get_latest_by': 'pk',
            },
        ),
    ]
