# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 06:29
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Order')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.URLField(blank=True)),
                ('logo', models.ImageField(upload_to='website/partner/', validators=[common.validators.FileSizeValidator(1)], verbose_name='Logo')),
                ('logo_crop', image_cropping.fields.ImageRatioField('image', '170x120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Logo crop')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'name',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Order')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
