# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_link_partner_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo_crop',
            field=image_cropping.fields.ImageRatioField('logo', '170x120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Logo crop'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Url'),
        ),
    ]
