# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20160518_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteheader',
            name='created',
        ),
        migrations.AddField(
            model_name='siteheader',
            name='end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='siteheader',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start'),
        ),
    ]
