# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20160519_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteheader',
            name='end',
            field=models.DateField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='siteheader',
            name='start',
            field=models.DateField(verbose_name='Start'),
        ),
    ]
