# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20160519_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='siteheader',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Site headers'},
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Welcomes'},
        ),
    ]
