# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 06:15
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20160713_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
            preserve_default=False,
        ),
    ]
