# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_link_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='video',
        ),
    ]
