# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_link_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Judul')),
                ('url', embed_video.fields.EmbedVideoField(verbose_name='URL')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'ordering': ['pk'],
                'get_latest_by': 'pk',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
    ]
