# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterrehabilitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterrehabilitation.Activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postassesment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterrehabilitation.PostAssesment', verbose_name='Post Assesment'),
        ),
    ]
