# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterrehabilitation', '0002_auto_20160428_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolevels.Province', verbose_name='Province'),
        ),
    ]
