# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20160427_1613'),
        ('disasterrehabilitation', '0003_auto_20160428_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAssesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('file', models.FileField(blank=True, null=True, upload_to='disasterrehabilitation/eventassesment/', verbose_name='File')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Event', verbose_name='Event')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.RemoveField(
            model_name='postassesment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='location',
            name='postassesment',
        ),
        migrations.DeleteModel(
            name='PostAssesment',
        ),
        migrations.AddField(
            model_name='location',
            name='eventassesment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterrehabilitation.EventAssesment', verbose_name='Event Assesment'),
        ),
    ]
