# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasterrehabilitation', '0008_auto_20160430_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'get_latest_by': 'updated', 'ordering': ['-updated', '-created'], 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name_plural': 'agencies'},
        ),
    ]
