# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterrehabilitation', '0009_auto_20160501_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='file',
            field=models.FileField(default='', upload_to='disasterrehabilitation/reference/', verbose_name='File'),
            preserve_default=False,
        ),
    ]
