# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterrehabilitation', '0010_auto_20160504_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN-PROGRESS', 'IN-PROGRESS'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
    ]
