# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasterrehabilitation', '0013_auto_20160531_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='eventassessment',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Event assessments'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'References'},
        ),
    ]
