# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolevels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecastReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('forecast_morning', models.CharField(choices=[('CERAH', 'Cerah'), ('CERAH BERAWAN', 'Cerah Berawan'), ('BERAWAN', 'Berawan'), ('HUJAN RINGAN', 'Hujan Ringan'), ('HUJAN SEDANG', 'Hujan Sedang'), ('HUJAN DERAS', 'Hujan Deras')], default='CERAH', max_length=50, null=True, verbose_name='Morning Forecast')),
                ('forecast_noon', models.CharField(choices=[('CERAH', 'Cerah'), ('CERAH BERAWAN', 'Cerah Berawan'), ('BERAWAN', 'Berawan'), ('HUJAN RINGAN', 'Hujan Ringan'), ('HUJAN SEDANG', 'Hujan Sedang'), ('HUJAN DERAS', 'Hujan Deras')], default='CERAH', max_length=50, null=True, verbose_name='Morning Forecast')),
                ('forecast_night', models.CharField(choices=[('CERAH', 'Cerah'), ('CERAH BERAWAN', 'Cerah Berawan'), ('BERAWAN', 'Berawan'), ('HUJAN RINGAN', 'Hujan Ringan'), ('HUJAN SEDANG', 'Hujan Sedang'), ('HUJAN DERAS', 'Hujan Deras')], default='CERAH', max_length=50, null=True, verbose_name='Night Forecast')),
                ('forecast', models.CharField(choices=[('CERAH', 'Cerah'), ('CERAH BERAWAN', 'Cerah Berawan'), ('BERAWAN', 'Berawan'), ('HUJAN RINGAN', 'Hujan Ringan'), ('HUJAN SEDANG', 'Hujan Sedang'), ('HUJAN DERAS', 'Hujan Deras')], default='CERAH', max_length=50, null=True, verbose_name='Forecast')),
                ('temperature_min', models.PositiveIntegerField(default=0, verbose_name='Temperature Min')),
                ('temperature_max', models.PositiveIntegerField(default=0, verbose_name='Temperature Max')),
                ('humidity_min', models.PositiveIntegerField(default=0, verbose_name='Humidity Min')),
                ('humidity_max', models.PositiveIntegerField(default=0, verbose_name='Humidity Max')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.City', verbose_name='City')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Province', verbose_name='Province')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'get_latest_by': 'updated',
            },
        ),
    ]
