# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='forecast_noon',
            field=models.CharField(choices=[('CERAH', 'Cerah'), ('CERAH BERAWAN', 'Cerah Berawan'), ('BERAWAN', 'Berawan'), ('HUJAN RINGAN', 'Hujan Ringan'), ('HUJAN SEDANG', 'Hujan Sedang'), ('HUJAN DERAS', 'Hujan Deras')], default='CERAH', max_length=50, null=True, verbose_name='Noon Forecast'),
        ),
    ]
