# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 10:19
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0002_auto_20160420_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='forecast',
            field=models.CharField(blank=True, choices=[('CERAH', 'Cerah'), ('CERAH BERAWAN', 'Cerah Berawan'), ('BERAWAN', 'Berawan'), ('HUJAN RINGAN', 'Hujan Ringan'), ('HUJAN SEDANG', 'Hujan Sedang'), ('HUJAN DERAS', 'Hujan Deras')], max_length=50, verbose_name='Forecast'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='forecast_morning',
            field=models.CharField(blank=True, choices=[('CERAH', 'Cerah'), ('CERAH BERAWAN', 'Cerah Berawan'), ('BERAWAN', 'Berawan'), ('HUJAN RINGAN', 'Hujan Ringan'), ('HUJAN SEDANG', 'Hujan Sedang'), ('HUJAN DERAS', 'Hujan Deras')], max_length=50, verbose_name='Morning Forecast'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='forecast_night',
            field=models.CharField(blank=True, choices=[('CERAH', 'Cerah'), ('CERAH BERAWAN', 'Cerah Berawan'), ('BERAWAN', 'Berawan'), ('HUJAN RINGAN', 'Hujan Ringan'), ('HUJAN SEDANG', 'Hujan Sedang'), ('HUJAN DERAS', 'Hujan Deras')], max_length=50, verbose_name='Night Forecast'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='forecast_noon',
            field=models.CharField(blank=True, choices=[('CERAH', 'Cerah'), ('CERAH BERAWAN', 'Cerah Berawan'), ('BERAWAN', 'Berawan'), ('HUJAN RINGAN', 'Hujan Ringan'), ('HUJAN SEDANG', 'Hujan Sedang'), ('HUJAN DERAS', 'Hujan Deras')], max_length=50, verbose_name='Noon Forecast'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='humidity_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Humidity Max'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='humidity_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Humidity Min'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='temperature_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Temperature Max'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='temperature_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Temperature Min'),
        ),
    ]
