# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0002_auto_20160420_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Province', verbose_name='Province'),
        ),
    ]
