# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0002_auto_20160503_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='temperature_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperature Max'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='temperature_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperature Min'),
        ),
    ]
