# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0003_auto_20160425_1719'),
        ('weatherforecast', '0003_auto_20160425_1235'),
    ]

    operations = [
    ]
