# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0004_auto_20160504_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='forecast',
            field=models.CharField(blank=True, choices=[('CERAH', 'Clear'), ('CERAH BERAWAN', 'Partly cloudy'), ('BERAWAN', 'Cloudy'), ('HUJAN RINGAN', 'Light rain'), ('HUJAN SEDANG', 'Moderate rain'), ('HUJAN LEBAT', 'Heavy rain')], max_length=50, verbose_name='Forecast'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='forecast_morning',
            field=models.CharField(blank=True, choices=[('CERAH', 'Clear'), ('CERAH BERAWAN', 'Partly cloudy'), ('BERAWAN', 'Cloudy'), ('HUJAN RINGAN', 'Light rain'), ('HUJAN SEDANG', 'Moderate rain'), ('HUJAN LEBAT', 'Heavy rain')], max_length=50, verbose_name='Morning forecast'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='forecast_night',
            field=models.CharField(blank=True, choices=[('CERAH', 'Clear'), ('CERAH BERAWAN', 'Partly cloudy'), ('BERAWAN', 'Cloudy'), ('HUJAN RINGAN', 'Light rain'), ('HUJAN SEDANG', 'Moderate rain'), ('HUJAN LEBAT', 'Heavy rain')], max_length=50, verbose_name='Night forecast'),
        ),
        migrations.AlterField(
            model_name='weatherforecastreport',
            name='forecast_noon',
            field=models.CharField(blank=True, choices=[('CERAH', 'Clear'), ('CERAH BERAWAN', 'Partly cloudy'), ('BERAWAN', 'Cloudy'), ('HUJAN RINGAN', 'Light rain'), ('HUJAN SEDANG', 'Moderate rain'), ('HUJAN LEBAT', 'Heavy rain')], max_length=50, verbose_name='Noon forecast'),
        ),
    ]
