# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlevel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watergate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='waterlevelreport',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Height'),
        ),
    ]
