# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlevel', '0002_auto_20160414_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlevelreport',
            name='weather',
            field=models.CharField(choices=[('T', 'Clear'), ('MT', 'Slightly cloudy'), ('M', 'Cloudy'), ('G', 'Drizzle'), ('H', 'Rain')], default='T', max_length=50, verbose_name='Weather'),
        ),
    ]
