# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlevel', '0003_auto_20160427_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watergate',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='waterlevelreport',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
    ]
