# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolevels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rw',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
