# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolevels', '0002_auto_20160223_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
