# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolevels', '0003_auto_20160223_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rw',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
