# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolevels', '0004_auto_20160223_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rw',
            name='area',
            field=models.DecimalField(decimal_places=10, max_digits=50),
        ),
    ]
