# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolevels', '0005_auto_20160223_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rw',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
