# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolevels', '0006_auto_20160224_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rw',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subdistrict',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
