# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolevels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaksafeReportAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('rw', models.TextField(blank=True, verbose_name='RW')),
                ('source', models.URLField(blank=True, default='', verbose_name='Source')),
                ('damage_infrastruktur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Infrastructure Damage')),
                ('loss_infrastruktur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Infrastructure Loss')),
                ('damage_lintas_sektor', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Trans-sector Damage')),
                ('loss_lintas_sector', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Trans-sector Loss')),
                ('damage_produktif', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Productive Damage')),
                ('loss_produktif', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Productive Loss')),
                ('damage_social_perumahan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Social Estate Damage')),
                ('loss_social_perumahan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Social Estate Loss')),
                ('damage_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Total Damage')),
                ('loss_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Total Loss')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Village', verbose_name='Village')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
    ]
