# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolevels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('magnitude', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.City')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Disaster')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Province')),
                ('rt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.RT')),
                ('rw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.RW')),
                ('subdistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Subdistrict')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Village')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('VER', 'Verified'), ('UNV', 'Unverified'), ('TBD', 'To Be Determined')], default='TBD', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Source'),
        ),
    ]
