# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:39
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 11, 39, 16, 937464, tzinfo=utc), verbose_name='Updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 11, 39, 27, 588463, tzinfo=utc), verbose_name='Updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disaster',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='event',
            name='disaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Disaster', verbose_name='Disaster'),
        ),
        migrations.AlterField(
            model_name='event',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='event',
            name='magnitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Magnitude'),
        ),
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='event',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='event',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.RT', verbose_name='RW'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.RW', verbose_name='RW'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Subdistrict', verbose_name='Subdistrict'),
        ),
        migrations.AlterField(
            model_name='event',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Village', verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='report',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='report',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Source', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified'), ('TBD', 'To be determined')], default='TBD', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='source',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
