# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Un', 'Unverified'), ('V', 'Verified'), ('Tbd', 'To be Determined')], max_length=50),
        ),
    ]
