# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disaster',
            old_name='code',
            new_name='PK',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='code',
            new_name='PK',
        ),
    ]
