# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160218_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='kejadian',
        ),
        migrations.AddField(
            model_name='report',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 18, 11, 10, 14, 245651, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
