# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 09:03
from __future__ import unicode_literals

import common.validators
from decimal import Decimal
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolevels', '0001_initial'),
        ('reports', '0002_auto_20160319_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/event_image', validators=[common.validators.MimetypeValidator(('text/plain', 'application/png')), common.validators.FileSizeValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt_text', models.TextField(blank=True, verbose_name='')),
                ('evac_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Evacution Point')),
                ('evac_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Evacution Total')),
                ('affected_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Affected Total')),
                ('affected_death', models.PositiveIntegerField(blank=True, null=True, verbose_name='Affected Death')),
                ('affected_injury', models.PositiveIntegerField(blank=True, null=True, verbose_name='Affected Injury')),
                ('loss_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.TextField(blank=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.City', verbose_name='City')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Province', verbose_name='Province')),
                ('rt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.RT', verbose_name='RT')),
                ('rw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.RW', verbose_name='RW')),
                ('subdistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Subdistrict', verbose_name='Subdistrict')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolevels.Village', verbose_name='Village')),
            ],
            options={
                'ordering': ['note'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
