# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160415_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='published',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
    ]
