# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 13:05
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_eventimage_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/event_image/', validators=[common.validators.MimetypeValidator('image/png'), common.validators.FileSizeValidator(1)], verbose_name='Image'),
        ),
    ]
