# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20160416_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='height_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Height'),
        ),
    ]
