# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20160503_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
    ]
