# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_eventimage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimage',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
    ]
