# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20160503_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='height_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum height'),
        ),
    ]
