# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20160503_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='eventimpact',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
    ]
