# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20160503_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.Event', verbose_name='Event'),
        ),
    ]
