# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 04:18
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20160516_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='unit in km', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='event',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='unit in cm', null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='event',
            name='height_min',
            field=models.PositiveIntegerField(blank=True, help_text='unit in cm', null=True, verbose_name='Minimum height'),
        ),
    ]
