# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 05:47
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20160621_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disaster',
            options={'verbose_name_plural': 'Disasters'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'pk', 'ordering': ['-pk'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'get_latest_by': 'pk', 'ordering': ['-pk'], 'verbose_name_plural': 'Event images'},
        ),
        migrations.AlterModelOptions(
            name='eventimpact',
            options={'get_latest_by': 'pk', 'ordering': ['-pk'], 'verbose_name_plural': 'Event impacts'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'pk', 'ordering': ['-pk'], 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Sources'},
        ),
        migrations.AlterField(
            model_name='event',
            name='magnitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='unit in Scala Richter', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Magnitude'),
        ),
    ]
