# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 06:46
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_auto_20160713_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit in km', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='event',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Unit in cm', null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='event',
            name='height_min',
            field=models.PositiveIntegerField(blank=True, help_text='Unit in cm', null=True, verbose_name='Minimum height'),
        ),
        migrations.AlterField(
            model_name='event',
            name='magnitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit in Scala Richter', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Magnitude'),
        ),
    ]
