# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20160730_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimpact',
            name='affected_total_in_kk',
            field=models.PositiveIntegerField(blank=True, help_text='In KK', null=True, verbose_name='Affected (in KK)'),
        ),
        migrations.AlterField(
            model_name='eventimpact',
            name='affected_total',
            field=models.PositiveIntegerField(blank=True, help_text='In Person', null=True, verbose_name='Affected (in Person)'),
        ),
    ]
