# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20160420_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Disaster Information', 'Disaster Information'), ('Waterlevel Information', 'Waterlevel Information')], default='Disaster Information', max_length=50, verbose_name='Subject'),
        ),
    ]
