# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20160422_2236'),
        ('contact', '0003_auto_20160422_1431'),
    ]

    operations = [
    ]
