# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('DISASTER_INFO', 'Disaster information'), ('WATER_LEVEL_INFO', 'Water level information')], default='DISASTER_INFO', max_length=50, verbose_name='Subject'),
        ),
    ]
