# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20160429_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
    ]
