# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 10:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsblast', '0002_auto_20160421_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactgroup',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contact_groups', to='smsblast.Contact', verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='smsblast.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smsblast.Template', verbose_name='Template'),
        ),
        migrations.DeleteModel(
            name='ContactGroup',
        ),
    ]
