# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 08:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsblast', '0003_auto_20160425_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact number'),
        ),
    ]
