# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsblast', '0004_auto_20160530_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'get_latest_by': 'pk', 'ordering': ['-pk'], 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'get_latest_by': 'pk', 'ordering': ['-pk'], 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'pk', 'ordering': ['-pk'], 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'get_latest_by': 'pk', 'ordering': ['-pk'], 'verbose_name_plural': 'Templates'},
        ),
    ]
