# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 05:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Content')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'get_latest_by': 'updated',
            },
        ),
    ]
