# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlywarning', '0002_auto_20160425_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earlywarningreport',
            options={'get_latest_by': 'pk', 'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='earlywarningreport',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
