# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earlywarning', '0003_auto_20160504_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earlywarningreport',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'EarlyWarningReports'},
        ),
    ]
