# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earlywarning', '0004_auto_20160713_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earlywarningreport',
            options={'get_latest_by': 'pk', 'ordering': ['pk'], 'verbose_name_plural': 'Early Warning Reports'},
        ),
    ]
